language: node_js
cache:
  directories:
    - ~/.npm
dist: trusty
sudo: required
notifications:
  email: false
node_js: 10
before_script:
  #- npm i -g polymer-cli
script:
  - npm run test:unit
after_success:
  - npm run dist
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release